
server.port=8080

# ===============================
# REDIS CONFIG
# ===============================
# Docker run ke liye (service name = redis)
spring.data.redis.host=localhost
spring.data.redis.port=6379
